version: '{build}'
configuration: Release
platform: x64
image:
- Visual Studio 2017
environment:
  matrix:
  - NAME: mkl
install:
- cmd: set CUDA=false
- cmd: set OPENCL=false
- cmd: set BLAS=false
- cmd: set GTEST=false
- cmd: IF NOT EXIST C:\cache\cutechess appveyor DownloadFile https://github.com/cutechess/cutechess/releases/download/gui-1.0.0/cutechess_setup.exe
- cmd: IF NOT EXIST C:\cache\cutechess cutechess_setup.exe /SUPPRESSMSGBOXES /DIR=C:\cache\cutechess /VERYSILENT
- cmd: set PATH=C:\cache\cutechess;%PATH%
- cmd: IF NOT EXIST C:\cache\mklml_win_2019.0.5.20190502 appveyor DownloadFile https://github.com/intel/mkl-dnn/releases/download/v0.20/mklml_win_2019.0.5.20190502.zip
- cmd: IF NOT EXIST C:\cache\mklml_win_2019.0.5.20190502 7z x mklml_win_2019.0.5.20190502.zip -oC:\cache
- cmd: IF NOT EXIST C:\cache\ispc-v1.11.0-windows appveyor DownloadFile http://sourceforge.net/projects/ispcmirror/files/v1.11.0/ispc-v1.11.0-windows.zip
- cmd: IF NOT EXIST C:\cache\ispc-v1.11.0-windows 7z x ispc-v1.11.0-windows.zip -oC:\cache
- cmd: set PATH=C:\cache\ispc-v1.11.0-windows\bin;%PATH%
- cmd: set PATH=C:\Python36;C:\Python36\scripts;%PATH%
- cmd: pip3 install --upgrade meson
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
- cmd: set PKG_FOLDER="C:\cache"
- cmd: IF NOT EXIST c:\cache\protobuf\ git clone -b v3.5.1 --single-branch --depth 1 https://github.com/google/protobuf.git
- cmd: IF NOT EXIST c:\cache\protobuf\ mkdir protobuf\build_msvc
- cmd: IF NOT EXIST c:\cache\protobuf\ cd protobuf\build_msvc
- cmd: IF NOT EXIST c:\cache\protobuf\ cmake -G "Visual Studio 15 2017 Win64" -Dprotobuf_BUILD_SHARED_LIBS=NO -Dprotobuf_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=c:/cache/protobuf ../cmake
- cmd: IF NOT EXIST c:\cache\protobuf\ msbuild INSTALL.vcxproj /p:Configuration=Release /p:Platform=x64 /m
- cmd: set PATH=c:\cache\protobuf\bin;%PATH%
- cmd: IF NOT EXIST c:\cache\testnet appveyor DownloadFile http://lczero.org/get_network?sha=7170f639ba1cdc407283b8e52377283e36845b954788c6ada8897937637ef032 -Filename c:\cache\testnet
- cmd: IF NOT EXIST C:\cache\syzygy mkdir C:\cache\syzygy
- cmd: cd C:\cache\syzygy
- cmd: IF NOT EXIST KQvK.rtbz curl --remote-name-all https://tablebase.lichess.ovh/tables/standard/3-4-5/K{P,N,R,B,Q}vK.rtb{w,z}
- cmd: IF NOT EXIST KQQvK.rtbz curl --remote-name-all https://tablebase.lichess.ovh/tables/standard/3-4-5/K{P,N,R,B,Q}{P,N,R,B,Q}vK.rtb{w,z}
- cmd: IF NOT EXIST KQvKQ.rtbz curl --remote-name-all https://tablebase.lichess.ovh/tables/standard/3-4-5/K{P,N,R,B,Q}vK{P,N,R,B,Q}.rtb{w,z}
- cmd: cd C:\projects\lc0
cache:
  - C:\cache
  - C:\projects\lc0\subprojects\packagecache
before_build:
- cmd: git submodule update --init --recursive
- cmd: meson build --backend vs2017 --buildtype release -Dgtest=false -Dopencl=false -Dblas=true -Dcudnn=false -Dispc_native_only=false -Dpopcnt=true -Dprotobuf_include="%PKG_FOLDER%\protobuf\include" -Dprotobuf_libdir="%PKG_FOLDER%\protobuf\lib" -Dmkl_include="%PKG_FOLDER%\mklml_win_2019.0.5.20190502\include" -Dmkl_libdirs="%PKG_FOLDER%\mklml_win_2019.0.5.20190502\lib" -Ddefault_library=static
build_script:
- cmd: msbuild "C:\projects\lc0\build\lc0.sln" /m /p:WholeProgramOptimization=PGInstrument /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: cd build
- cmd: copy C:\cache\mklml_win_2019.0.5.20190502\lib\*.dll
- cmd: cutechess-cli -rounds 1 -engine cmd=lc0 -engine cmd=lc0 -each arg="--weights=c:\cache\testnet" arg="--syzygy-paths=C:\cache\syzygy" tc=60+1 proto=uci timemargin=100 -debug
- cmd: cd ..
- cmd: msbuild "C:\projects\lc0\build\lc0.sln" /m /p:WholeProgramOptimization=PGOptimize /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_build:
- cmd: 7z a lc0-windows-%NAME%.zip %APPVEYOR_BUILD_FOLDER%\build\lc0.exe
artifacts:
  - path: build/lc0.exe
    name: lc0-$(NAME)
  - path: lc0-windows-$(NAME).zip
    name: lc0-windows-$(NAME)-zip
