version: '{build}'
configuration: Release
platform: x64
image:
- Visual Studio 2017
environment:
  matrix:
  - NAME: android
clone_folder: c:\projects\lc0
install:
- cmd: set PATH=C:\Python36;C:\Python36\scripts;%PATH%
- cmd: pip3 install --upgrade meson
- cmd: C:\ProgramData\Microsoft\AndroidNDK64\android-ndk-r17\build\tools\make_standalone_toolchain.py --arch arm64 --api 21 --stl libc++ --install-dir \android-standalone-64
- cmd: set PATH=C:\android-standalone-64\bin;%PATH%
- cmd: cd C:\projects\lc0
before_build:
- cmd: git submodule update --init --recursive
- cmd: meson build --buildtype release -Dgtest=false -Deigen=true -Ddefault_library=static --cross-file cross-files/aarch64-linux-android
build_script:
- cmd: cd build
- cmd: ninja
artifacts:
  - path: build/lc0
    name: lc0-$(NAME)


