version: '{build}'
configuration: Release
platform: x64
image:
- Visual Studio 2019
clone_folder: c:\projects\lc0
install:
- cmd: IF NOT EXIST C:\cache\ispc-v1.13.0-windows appveyor DownloadFile https://github.com/ispc/ispc/releases/download/v1.13.0/ispc-v1.13.0-windows.zip
- cmd: IF NOT EXIST C:\cache\ispc-v1.13.0-windows 7z x ispc-v1.13.0-windows.zip -oC:\cache\ispc-v1.13.0-windows
- cmd: set PATH=C:\cache\ispc-v1.13.0-windows\bin;%PATH%
- cmd: set PATH=C:\Python36;C:\Python36\scripts;%PATH%
- cmd: pip3 install --upgrade meson==0.55.3
- cmd: set PATH=%PATH%;C:\msys64\mingw64\bin;C:\msys64\usr\bin
- cmd: set PATH=%PATH%;"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja"
- cmd: cd C:\projects\lc0
cache:
  - C:\cache
  - C:\projects\lc0\subprojects\packagecache
before_build:
- cmd: git submodule update --init --recursive
- cmd: rem echo.#define DEFAULT_MINIBATCH_SIZE 1 & echo.#define DEFAULT_MAX_PREFETCH 0 > params_override.h
- cmd: meson build --buildtype release -Dgtest=false -Ddx=false -Dblas=true -Dispc_native_only=false -Dpopcnt=true -Ddefault_library=static
build_script:
- cmd: cd C:\projects\lc0\build
- cmd: ninja
- cmd: cp lc0.exe ..
- cmd: cd C:\projects\lc0
artifacts:
  - path: lc0.exe
    name: lc0-$(NAME)

