version: '{build}'
configuration: Release
platform: x64
image:
- Visual Studio 2019
clone_folder: c:\projects\lc0
environment:
  matrix:
  - ARCH: x86-64-avx512-vnni
  - ARCH: x86-64-avx512
  - ARCH: x86-64-vnni
  - ARCH: x86-64-bmi2
  - ARCH: x86-64-avx2
  - ARCH: x86-64-avx
  - ARCH: x86-64-modern
install:
- cmd: IF NOT EXIST C:\cache\ispc-v1.13.0-windows appveyor DownloadFile https://github.com/ispc/ispc/releases/download/v1.13.0/ispc-v1.13.0-windows.zip
- cmd: IF NOT EXIST C:\cache\ispc-v1.13.0-windows 7z x ispc-v1.13.0-windows.zip -oC:\cache\ispc-v1.13.0-windows
- cmd: set PATH=C:\cache\ispc-v1.13.0-windows\bin;%PATH%
- cmd: set PATH=C:\Python36;C:\Python36\scripts;%PATH%
- cmd: pip3 install --upgrade meson==0.55.3
- cmd: set PATH=%PATH%;C:\msys64\mingw64\bin;C:\msys64\usr\bin
- cmd: set PATH=%PATH%;"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja"
- cmd: cd C:\projects\lc0
cache:
  - C:\cache
  - C:\projects\lc0\subprojects\packagecache
before_build:
- cmd: git submodule update --init --recursive
- cmd: meson build --buildtype release -Dgtest=false -Ddx=false -Dblas=true -Dispc_native_only=false -Dpopcnt=true -Ddefault_library=static -Darch=%ARCH%
build_script:
- cmd: cd C:\projects\lc0\build
- cmd: ninja
- cmd: cp lcfish.exe ..\lcfish-%ARCH%.exe
- cmd: cd C:\projects\lc0
artifacts:
  - path: lcfish-$(ARCH).exe
    name: lcfish-$(ARCH)
deploy:
  - provider: GitHub
    artifact: lcfish-$(ARCH).exe
    auth_token:
      secure: cDBBHS9pbSEEe+Dt/kGjHCrSPqaTQuZsrvFETud2tfVwTTnm7JneWQLB1n6Z+L6/
    on:
      appveyor_repo_tag: true
