version: 2
jobs:
  build:
    machine:
      image: linux-cuda-11:default
      resource_class: medium
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: git submodule update --init
      - run:
          name: Install build tools
          command: |
            pip3 install meson==0.58.1
            pip3 install ninja
      - run:
          name: Meson GCC
          command: meson build-gcc -Dgtest=false
      - run:
          name: Build GCC
          command: |
            cd build-gcc
            ninja
  "mac":
    macos:
      xcode: 14.1.0
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: git submodule update --init --no-single-branch
      - run:
          name: Install build tools
          command: |
            pip3 install meson==0.63
            pip3 install ninja
            curl -LJOs https://github.com/ispc/ispc/releases/download/v1.21.0/ispc-v1.21.0-macOS.universal.tar.gz
            tar xf ispc-v1.21.0-macOS.universal.tar.gz
            cp ispc-v1.21.0-macOS.universal/bin/ispc /usr/local/bin
      - run:
          name: Build lc0
          command: |
            meson build --buildtype=release -Dgtest=false -Dopencl=false
            cd build
            ninja
      - run:
          name: Build lc0 arm
          command: |
            meson build-arm --buildtype=release -Dgtest=false -Dopencl=false --cross-file cross-files/aarch64-darwin
            cd build-arm
            ninja
      - run:
          name: Make universal binary
          command: lipo -create -o /tmp/lc0 build/lc0 build-arm/lc0
      - store_artifacts:
          path: /tmp/lc0
          destination: lc0-macos_12.5.1
workflows:
  version: 2
  builds:
    jobs:
      - build
      - "mac"
